version: "3.8"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - grafana-net
    volumes:
      - grafana-volume

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: always
    ports:
      - 80:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126
    networks:
      - grafana-net
    volumes:
      - /c/Users/dragg/dht22_grafana/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf

networks:
  grafana-net:

volumes:
  grafana-volume:
    external: true